# app/Dockerfile

FROM python:3.12.7-slim

WORKDIR /app

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

# Configure sparse-checkout to pull only specific files
RUN git init . \
    && git remote add origin https://github.com/sacha-sz/UPM-DL.git \
    && git config core.sparseCheckout true \
    && echo "requirements.txt" >> .git/info/sparse-checkout \
    && echo "streamlit.py" >> .git/info/sparse-checkout \
    && echo "cnn_new_model.pth" >> .git/info/sparse-checkout \
    && git pull origin main

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Streamlit port
EXPOSE 8501

# Add a healthcheck
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1

# Run the Streamlit app
ENTRYPOINT ["streamlit", "run", "streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
